apiVersion: 1

datasources:
  - uid: tempo-workshop
    name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: true
    version: 1
    editable: false
    jsonData:
      httpMethod: GET
      nodeGraph:
        enabled: true
      traceQuery:
        timeShiftEnabled: true
        spanStartTimeShift: 1h
        spanEndTimeShift: -1h
      spanBar:
        type: Duration
      tracesToLogsV2:
        datasourceUid: loki-workshop
        spanStartTimeShift: -1m
        spanEndTimeShift: 1m
        filterByTraceID: false
        filterBySpanID: true
        customQuery: true
        query: '{$${__tags}, trace_id="$${__trace.traceId}", span_id="$${__span.spanId}"}'
        tags:
          - key: service.name
            value: service_name
  - uid: loki-workshop
    name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: false
    version: 1
    editable: false
    jsonData:
      derivedFields:
        - name: TraceID
          matcherRegex: '"trace_id":"([a-f0-9]+)"'
          url: '$${__value.raw}'
          datasourceUid: tempo-workshop
          urlDisplayLabel: Open trace in Tempo
